environment:
  nodejs_version: "12"

version: 1.0.{build}-alpha

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - ps: node --version
  - ps: npm install
  - ps: npm run build

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - develop
build: off